language: csharp
solution: SimpleECS.sln
install:
  - nuget restore SimpleECS.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release SimpleECS.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./SimpleECSTests/bin/Release/SimpleECSTests.dll